#!/bin/sh
#1000101.sh
#Slurm script to run R program that generates graph of discrete Delta-hedging call

#Slurm directives
#
#SBATCH --account=stats      # The account name for the job.
#SBATCH --job-name=hedge    # The job name.
#SBATCH -c 8                     # The number of cpu cores to use.
#SBATCH --time=20:00:00              # The time the job will take to run.
#SBATCH --mem-per-cpu=8gb        # The memory the job will use per cpu core.
module load R

#Command to execute R code
R CMD BATCH --no-save --vanilla 1000101.R 1000101out

# End of script
